# Generated by Django 4.2 on 2023-04-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(default='', max_length=10)),
                ('plan', models.CharField(max_length=50)),
                ('joindate', models.DateField(max_length=40)),
                ('expiredate', models.DateField(max_length=40)),
                ('initialamount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(default='', max_length=10)),
                ('plan', models.CharField(max_length=50)),
                ('joindate', models.DateField(max_length=40)),
                ('expiredate', models.DateField(max_length=40)),
                ('initialamount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemberEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateField(max_length=40)),
                ('entrytime', models.TimeField(max_length=40)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.member')),
            ],
        ),
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateField(max_length=40)),
                ('entrytime', models.TimeField(max_length=40)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.guest')),
            ],
        ),
    ]
