# Generated by Django 4.2 on 2023-04-27 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='expiredate',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='initialamount',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='joindate',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='guestentry',
            name='entrydate',
        ),
        migrations.RemoveField(
            model_name='guestentry',
            name='entrytime',
        ),
        migrations.RemoveField(
            model_name='memberentry',
            name='entrydate',
        ),
        migrations.RemoveField(
            model_name='memberentry',
            name='entrytime',
        ),
        migrations.AddField(
            model_name='employee',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='guest',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='guest',
            name='price',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='memberentry',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='initialamount',
            field=models.IntegerField(blank=True, default=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
