# Generated by Django 4.2 on 2023-04-28 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_employee_gender_alter_guest_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 7, 0, 9, 507805, tzinfo=datetime.timezone.utc)),
        ),
    ]
