# Generated by Django 4.2 on 2023-04-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_member_expiredate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberentry',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberEntry',
        ),
    ]
