# Generated by Django 4.2 on 2023-04-29 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_employee_age_alter_guest_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestentry',
            name='guest',
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='GuestEntry',
        ),
    ]
