# Generated by Django 4.2 on 2023-04-29 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('plan', models.CharField(blank=True, default='', max_length=50)),
                ('joindate', models.DateField(default=django.utils.timezone.now)),
                ('expiredate', models.DateField(default=datetime.datetime(2024, 4, 28, 6, 58, 10, 887249, tzinfo=datetime.timezone.utc))),
                ('initialamount', models.IntegerField(blank=True, default=40)),
            ],
        ),
        migrations.CreateModel(
            name='MemberEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
