# Generated by Django 4.2 on 2023-04-29 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 8, 21, 2, 449727, tzinfo=datetime.timezone.utc)),
        ),
    ]
