# Generated by Django 4.2 on 2023-04-29 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 16, 51, 52, 19770, tzinfo=datetime.timezone.utc)),
        ),
    ]
