# Generated by Django 4.2 on 2023-04-29 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_alter_member_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberentry',
            name='checked_in_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 16, 54, 17, 424252, tzinfo=datetime.timezone.utc)),
        ),
    ]
