# Generated by Django 4.2 on 2023-04-29 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_expiredate_alter_member_joindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 17, 41, 45, 842181)),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2023, 4, 29, 17, 41, 45, 842170)),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 29, 17, 41, 45, 842719)),
        ),
    ]
