# Generated by Django 4.2 on 2023-04-29 17:49

from django.db import migrations, models
import django.utils.timezone
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_age_alter_member_expiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateTimeField(default=members.models.one_year_from_now),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
